name: Push Image To Container Registry

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.dockerfile'

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "${{ github.repository_owner }}/alpine-bazel"
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: alpine-bazel.dockerfile
          tags: ghcr.io/${{env.IMAGE_NAME}}:latest
          push: true
